spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security-demo
    username: security-user
    password: Abc1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true